#|  
Salomón Charabati
Programming Languages
Guess-game program
|#


; Function for calling the program.
(define (guess-game num)
    (display "WELCOME TO THE NUMBER GUESS GAME \n")
    (define random_number (random 1 100))
    ;(printf "The random number generated is ~a \n" random_number) ; For testing only
    (iterative_function random_number 1) ; Entry point for iterative function
)

; Iterative function. Recieves the random number generated by (guess-game) and receives a counter
(define (iterative_function random_number counter)
    (display "Enter your guess\n")
    (define guess (read))
    (if (= random_number guess)
        ; If true
        (printf "Congratulations, you won after ~a tries\n" counter)
        ; If false
        (begin
        (if (< random_number guess)
            (display "Enter a lower number\n")
            (display "Enter a higher number\n") 
         )
        (iterative_function random_number (+ 1 counter))) ; Call the function again and add 1 to counter
    )
)

